services:
  - type: web
    name: whatsapp-bot-api
    env: node
    plan: free
    buildCommand: |
      # Instalar dependências do Node.js
      npm install
      
      # Instalar Chrome e dependências no Ubuntu (OnRender usa Ubuntu)
      echo "📦 Instalando Google Chrome e dependências..."
      
      # Atualizar lista de pacotes
      apt-get update
      
      # Instalar dependências necessárias para o Chrome
      apt-get install -y \
        wget \
        gnupg \
        ca-certificates \
        fonts-liberation \
        libasound2 \
        libatk-bridge2.0-0 \
        libatk1.0-0 \
        libatspi2.0-0 \
        libcups2 \
        libdbus-1-3 \
        libdrm2 \
        libgbm1 \
        libgtk-3-0 \
        libnspr4 \
        libnss3 \
        libwayland-client0 \
        libxcomposite1 \
        libxdamage1 \
        libxfixes3 \
        libxkbcommon0 \
        libxrandr2 \
        xdg-utils \
        libu2f-udev \
        libvulkan1
      
      # Baixar e instalar Google Chrome Stable
      wget -q -O /tmp/google-chrome-stable_current_amd64.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      apt-get install -y /tmp/google-chrome-stable_current_amd64.deb
      rm /tmp/google-chrome-stable_current_amd64.deb
      
      # Verificar instalação
      which google-chrome-stable
      google-chrome-stable --version
      
      echo "✅ Chrome instalado com sucesso!"
    
    startCommand: NODE_ENV=production node server.js
    
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromGroup: web
    
    # Aumentar recursos se possível (requer plano pago)
    # disk:
    #   name: chrome-data
    #   mountPath: /opt/render/project/chrome-profile
    #   sizeGB: 1
